=== UPPIGIT/Integration/v01/tool-iib-master/tool-iib-master/NodeFeatures_V1_IS/NodeFeatures_V1_IS_InlineSchema1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://NodeFeatures_V1_IS" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://NodeFeatures_V1_IS"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
	<xsd:include schemaLocation="doc/mappingDemo-input.xsd"></xsd:include>
	<xsd:include schemaLocation="doc/mappingDemo-output-space_separated.xsd"></xsd:include>
	
	<xsd:element ibmSchExtn:docRoot="true" name="xsltDemo">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="input1" nillable="true">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="10" minOccurs="1" name="cd">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="title" type="xsd:string">
										</xsd:element>
										<xsd:element name="artist" type="xsd:string">
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element ibmSchExtn:docRoot="true" name="xsltDemoResponse">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="output1" nillable="true" type="xsd:string" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element ibmSchExtn:docRoot="true" name="mappingDemoRequest" nillable="true">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tns:mappingDemoInput"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element ibmSchExtn:docRoot="true" name="mappingDemoResponse" nillable="true">		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tns:mappingDemoOutput"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== UPPIGIT/Integration/v01/tool-iib-master/tool-iib-master/NodeFeatures_V1_IS/xmlDemoRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:xsltDemo xmlns:tns="http://NodeFeatures_V1_IS"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://NodeFeatures_V1_IS NodeFeatures_V1_IS_InlineSchema1.xsd ">
	<input1>
		<cd>
			<title>title01</title>
			<artist>artist01</artist>
		</cd>
		<cd>
			<title>title02</title>
			<artist>artist02</artist>
		</cd>
		<cd>
			<title>title03</title>
			<artist>artist03</artist>
		</cd>
	</input1>
</tns:xsltDemo>
